### ISSUE TITLE
The `npm run serve` command hides almost all logging

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1236]
**Describe the bug**
The `npm run serve` command hides almost all logging

**To Reproduce**
Run the `npm run serve` command

**Expected behavior**
This behavior is not acceptable.

1. There is no feedback as to what is happening. 
    1. There is no useful troubleshooting information shown
    1. There is no indication of the state of progress

Neither the development nor DevOps teams will therefore have the best information to troubleshoot issues. We require:
1. Full logging to the screen indicating what is happening
1. No clearing of the output between messages

**Actual behavior**
1. First this message is seen
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/b7db4176-1067-4b88-88c5-2f159f092e8f)
1. Then the message is cleared, then this message is seen for a few seconds, then disappears
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/9902f7fe-ed3f-4994-9b99-10edd55df004)
1. The screen then goes blank for several minutes with no indication of what is happening. The user may feel that the operation is failing.
1. This message is then displayed for several minutes with no indication of any activity happening
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/7f1d5a4d-74e7-4ec0-bdd1-acfc33b4fe0a)
1. Finally, the screen clears once more then this message is visible
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/5a7669c3-8051-466a-acf5-488788407980)

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Tarunmeena0901** [comment]
@palisadoes @noman2002 i will like to work on this issue,
 thank you

**Comment by Tarunmeena0901** [comment]
hi @palisadoes @noman2002 i need little help here, the issue is almost solved as i had made changes in web.config.js and and integrate a state progress indicator in the console which shows the compilation progress and runtime error as well here are some screenshots 

![Screenshot 2023-12-24 161700](https://github.com/PalisadoesFoundation/talawa-admin/assets/97682967/ba30a3d4-2f7d-42ca-86be-0b27c8089d8d)

![Screenshot 2023-12-24 161725](https://github.com/PalisadoesFoundation/talawa-admin/assets/97682967/8153285e-f0a4-498c-8096-7b73942fcec5)

![Screenshot 2023-12-24 161753](https://github.com/PalisadoesFoundation/talawa-admin/assets/97682967/dc00a902-78b2-4052-a617-1cc6a4b4557e)

the only part left is to make is available for everyone but the changes made are in node_module/react-scripts/config/webpack.config.js
as we know we cannot commit node_module the how can make these changes commit in the repo

i thought of adding webpack.config.js in the root directory but it wont workt cause "npm run serve" command initiate the "react-scritps start" command (in package_json) . 
can you help me with this please

**Comment by Tarunmeena0901** [comment]
ok so i came up with an solution in pull request . happy to take any suggestions
