### ISSUE TITLE
Admin: Redesign Organization CRUD screens

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1457]
### Is your feature request related to a problem? Please describe.

This is a two part issue:

#### PART 1

We need to update the Organization CRUD screens to match our reference Figma design that can be found on our documentation site:
- https://docs.talawa.io/docs/design/ux/ux-design-system

#### PART 2

We need to add support for Organization `Addresses` that replaces the previous Organization `Location` field in the API

1. Support for the `Address` functionality in the Organization was created in this PR which had to be reverted because an equivalent Admin issue like this one hadn't been created at the time.
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1666
1. When tackling this issue you can test your changes against this PR in a branch of your local API repository and coordinate with the person assigned this API PR to merge your PR and a renewed API PR

### Describe the solution you'd like

There are a few affected screens:

#### Organization Settings 

1. Update the Organization Settings screen replacing the API location field with the proposed API Address fields
    1. http://localhost:3000/orgsetting/id=6537904485008f171cf29924 Using the sample demo data
    1.  https://github.com/PalisadoesFoundation/talawa-api/pull/1666

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/eaeeca89-92c2-45fc-b6c0-ed07ba9fbaa0)

#### Create Organization

1. Update the Create Organization screen to match the UI/UX of the Organization Settings screen
    1. http://localhost:3000/orglist

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/eba9ccb0-942c-488a-9349-354431b86f8c)

1. To look more in keeping with the new design theme. 
    1. Making the appropriate changes to the location field.
    3. Maintaining all other functionality including Create Sample Organization

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/b7830fb8-71fc-4914-9fa7-a9f639d19c77)

### Dashboard View

1. Update the dashboard view to reflect summary `Address` information  versus `Location`
    1. http://localhost:3000/orglist

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/8a9290d9-4447-4f4c-89aa-a4712dbca4af)

### Edit Organization User Screen

1. Update the screen to reflect summary `Address` information  versus `Location`
    1. http://localhost:3000/users

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/fe54ce39-7e2f-4899-9bbe-d0a5119b97a0)

### Organization Screen

1. Update the screen to reflect summary `Address` information  versus `Location`
    1. http://localhost:3000/orgdash/id=6537904485008f171cf29924 (Using sample data)

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/d7e422cc-c1e0-40a2-874a-f06dd7608035)

### Describe alternatives you've considered

- N/A

### Approach to be followed (optional)

- N/A

### Additional context

1. All other functionality must be maintained
2. The level of code coverage for the edited files must not fall
3. All tests must be valid tests of the functionality of our code base
1. We will need to add your Figma page designs to our official Figma document
2. Please plan for this

### Potential internship candidates

Please read this if you are planning to apply for a Palisadoes Foundation internship

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@Anubhav-2003 This is the issue we discussed

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, I would like to work on this issue.

**Comment by AVtheking** [comment]
Hey @Anubhav-2003 if you want help in this ,I am ready to help

**Comment by shawakash** [comment]
@palisadoes  what to do?
<img width="1283" alt="Screenshot 2024-01-20 at 3 44 47 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/112852873/b89a00a2-cde5-4fe5-9938-975bf02b5c3d">

i have setup the backend using docker and apollo serve is running

**Comment by AVtheking** [comment]
In your local database go to the user model and update the field adminApproved to true

**Comment by Anubhav-2003** [comment]
@AVtheking Absolutely sir, actually I am updating the files at the moment with the required mutations, and queries. I will definitely seek your help if I feel overwhelmed, or have any doubts. 

Thank you a lot for asking.

**Comment by palisadoes** [comment]
@Anubhav-2003 

1. We will need to add your Figma page designs to our official Figma document
2. Please plan for this

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, 

While working on the issue I have made most of the changes related to queries, and mutations. But, recently I am encountering the error, user:not found while creating organizations, is it a known issue, or got something to do with the latest changes made in the tokens, or local storage to fix infinite reload glitch. Because due to these bugs a lot of my work is currently getting hampered. 

Thank You.

**Comment by AVtheking** [comment]
fetch the latest upstream of the talawa api and if you are using docker to run the server then rebuild the images and restart the server

**Comment by Anubhav-2003** [comment]
@AVtheking Ok sir, Thank you a lot.

**Comment by AVtheking** [comment]
And also If you are using sample data then import the latest sample data

**Comment by Anubhav-2003** [comment]
@AVtheking Respected Sir, I just wanted one help. Can you please tell me where are the translations stored. I mean the keys and their values. For instance, the placeholders and labels in updateOrg, and createOrg, are using the useTranslation git hook to specify keys for fetching the translated string. But in the locales folder of talawa-api, I only found keys for erro codes. 

Your help will be appreciated. Thank You.

**Comment by palisadoes** [comment]
@Anubhav-2003 

- Look in `talawa-admin/public/locales`

**Comment by Anubhav-2003** [comment]
@palisadoes ok sir, thank you for your help.

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, I have made all the changes required for a successful implementation of the address field, and its use in the ADMIN portal. I am attaching the images of the UI form fields, as I saw it fit. I had a few questions. What approach should we use to store the address, and which fields should we make mandatory. 

I have a few options:
First, one is we can call an API for the list of countries, and their respective states / provinces, and then give user the freedom to write their own city name, postal code, and other street level specificity. ( To me, this sounds the most practical.)

Second, call an API to fetch exact street level details (Most professional, and production grade) but maybe expensive, and many remote places might not be accurately present in the data. 

Also, in the user table there is not enough space to show the complete address, so at the moment I am just displaying the city name. Please let me know if you propose otherwise.

I am trying to make the colors and design of "createOrganization Modal" to look like the settings page "Update Org", but it is a bit more complicated than expected. So, at the moment I am focusing more on the actual tangible implementations than aesthetics. I will come back to it, once all other things are sorted.
![Screenshot from 2024-01-23 18-54-21](https://github.com/PalisadoesFoundation/talawa-admin/assets/76914348/cbed9df6-f8c1-4332-989d-1280cd1c88fe)
![Screenshot from 2024-01-23 18-42-52](https://github.com/PalisadoesFoundation/talawa-admin/assets/76914348/dc17d522-27ad-4f9e-876c-64bc219c87ae)
![Screenshot from 2024-01-23 14-18-24](https://github.com/PalisadoesFoundation/talawa-admin/assets/76914348/962d40de-92b2-44ef-b9fb-42dd4a94914a)
![Screenshot from 2024-01-23 14-18-00](https://github.com/PalisadoesFoundation/talawa-admin/assets/76914348/d9c4f1f6-f6af-4a0e-af27-163167a40a12)

Thank You.

**Comment by palisadoes** [comment]
1. Use the API PR that is replacing the location type in the organization schema with an address type. Use your best judgement
1. We want the look and feel in the issue description.
1. Open a PR when ready. 

Please use your initiative to find an acceptable solution for the PR reviewers

**Comment by Anubhav-2003** [comment]
@palisadoes ok sir, thank you.
