### ISSUE TITLE
No validation for formState.link as URL or String

### ISSUE THREAD

**Issue by Keshav-0907** [PalisadoesFoundation/talawa-admin#1479]
**Describe the bug**
When creating a new advertisement, there is a missing validation check for the formState.link field. This allows users to input random strings or potentially invalid data.

**To Reproduce**

1. Create an Organization
2. Go to `orgads/id=some_id`.
3. Click on `Create new advertisement`.
4. Now you can eneter any random string in the `Provide a link for content to be displayed` input.

**Expected behavior**
The formState.link should undergo a validation to ensure that the provided input is a legitimate URL, preventing the submission of arbitrary or invalid strings.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/91189139/f3fb4a1c-1050-45f1-b75d-3544cf181424

**Comment by palisadoes** [comment]
We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

This policy is stated as a pinned post in all our Talawa repositories. Our YouTube videos explain why this practice is not acceptable to our Community.

This has been done 3 times.

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue

**Comment by pushkar707** [comment]
Hi, I want to work over this issue

**Comment by Keshav-0907** [comment]
> We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:
> 
> 1. We start looking for people to review PRs when you submit them.
> 2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
> 3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.
> 
> Please be considerate of our volunteers' limited time and our desire to improve our code base.
> 
> This policy is stated as a pinned post in all our Talawa repositories. Our YouTube videos explain why this practice is not acceptable to our Community.
> 
> This has been done 3 times.

> We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:
> 
> 1. We start looking for people to review PRs when you submit them.
> 2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
> 3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.
> 
> Please be considerate of our volunteers' limited time and our desire to improve our code base.
> 
> This policy is stated as a pinned post in all our Talawa repositories. Our YouTube videos explain why this practice is not acceptable to our Community.
> 
> This has been done 3 times.

Apologies for closing PRs without validation. I understand the impact on collaboration. I assure you it won't happen again. I appreciate your understanding. Thanks.

**Comment by SanjeevKrSingh** [comment]
Hi @palisadoes  I want to contribute on this issue can you plz assign it to me.
