### ISSUE TITLE
Admin Redesign: Redesiging the People Management Screen

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1550]
**Is your feature request related to a problem? Please describe.**
we want consistent design for  people management

**Describe the solution you'd like**
redesign the people management as of the designs in the figma file

**Additional context**
![Screenshot 2024-02-06 at 10 09 00 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/33c441fa-d0b2-4d6f-9e62-5df2aac679af)

link to the figma file: https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=307-212&mode=design&t=jw1Q8PosWMSmrFRM-0

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@palisadoes can i work on this

**Comment by AmitSharma512** [comment]
@palisadoes can I work on this issue ??

**Comment by crocmons** [comment]
@palisadoes can I work on it?

**Comment by MSVaibhav4141** [comment]
I would like to work on this.

**Comment by duplixx** [comment]
@aashimawadhwa this radio-buttons were not planned in designs where should i put these

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/b9ea22f5-942e-42d0-b9ea-32cb838088b3)

**Comment by duplixx** [comment]
@aashimawadhwa @palisadoes, I'd like to suggest a UI enhancement: transitioning from tables to cards. Tables aren't always the optimal way to present data, and cards offer a more visually appealing and user-friendly layout, especially considering the recent changes to the UI. Moreover, if we revert to a table format, we'll need to ensure that actions are appropriately placed. However, in the Figma UI, there isn't any provision for selecting fields to perform a single action across multiple items. Hence, sticking with the cards layout seems like the best option since it's already aligned with our current UI. Let me know your thoughts on this suggestion!

here are my current changes 
(little tweaks are still left here)

![WhatsApp Image 2024-02-07 at 13 33 36_30378182](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/7eab97cc-a00c-49cf-a064-e446d8f92b36)

**Comment by varshith257** [comment]
@aashimawadhwa  I think it is a duplicate issue of #1451

**Comment by duplixx** [comment]
@varshith257 I think there are multiple steps we need to take care of #1451:

1.Redesign Orgpeople and remove the actions button.
2.The user profile CRUD page should match that of the Figma design with the following modifications.

I have already worked on first part . We can divide it into two steps and you can work on 2nd part

**Comment by palisadoes** [comment]
> @varshith257 I think there are multiple steps we need to take care of #1451:
> 
> 1.Redesign Orgpeople and remove the actions button. 2.The user profile CRUD page should match that of the Figma design with the following modifications.
> 
> I have already worked on first part . We can divide it into two steps and you can work on 2nd part

One issue per assignee. Create a separate issue if you feel 2 PRs are required, one each per assignee.

**Comment by varshith257** [comment]
@palisadoes  Already #1451 consists of this issue. Your suggestion required

**Comment by varshith257** [comment]
I think it's a duplicate issue to it. But @duplixx  already completed half of the task as in #1451 of redesigning the people management screen. I'll take over from here and ensure that their efforts are not in vain. Together, we can build on the progress

**Comment by duplixx** [comment]
@varshith257 yeah sure !!
After finishing second point raise the PR naming like `User Profile Figma update`

> I think it's a duplicate issue to it. But @duplixx already completed half of the task as in #1451 of redesigning the people management screen. I'll take over from here and ensure that their efforts are not in vain. Together, we can build on the progress

**Comment by Cioppolo14** [comment]
@duplixx @varshith257 Please mention this plan in your PR description so we can keep track of it all.  Thank you for working together so both of you can contribute.
