### ISSUE TITLE
Bug Report: User Able To Access Admin Portal

### ISSUE THREAD

**Issue by rahulch07** [PalisadoesFoundation/talawa-admin#1584]
**Describe the bug**
When a user navigates to events section and goes to calender view, he is able to access the Admin Portal.

**To Reproduce**

1. Login as a user.
2. Navigate to 'Events' section.
3. Change from List View to Calender View.
4. Choose the event.
5. Click 'Show Event Dashboard'.

**Expected behavior**
User should be able to see 'Register/Already registered' option.

**Actual behavior**
User is able to see 'Show Event Dashboard' option.

**Screenshots**
![Screenshot 2024-02-14 160724](https://github.com/PalisadoesFoundation/talawa-admin/assets/87270395/142e242e-7384-47f9-aec9-5caa7d7bc733)
![Screenshot 2024-02-14 160806](https://github.com/PalisadoesFoundation/talawa-admin/assets/87270395/373ebe9f-a030-4d52-aec1-8c62f43bb743)
![Screenshot 2024-02-14 160828](https://github.com/PalisadoesFoundation/talawa-admin/assets/87270395/0bd615b0-48de-4e33-b200-bc13d04b72d6)
![Screenshot 2024-02-14 162104](https://github.com/PalisadoesFoundation/talawa-admin/assets/87270395/d32fd0c4-c0ad-4a7a-ac13-c541430396b0)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rahulch07** [comment]
@Cioppolo14 Please assign me this issue.

**Comment by takshakmudgal** [comment]
I'd like to work on this issue.

**Comment by Cioppolo14** [comment]
I am looking into how we want to handle this.  I will assign it depending on upon the outcome.

**Comment by varshith257** [comment]
@Cioppolo14   Based on the information provided, I have reproduced the issue on my end and found that it only occurs when the userRole is set to 'admin'. Specifically, when an admin logs in as a user and navigates to the calendar view, it redirects them to the admin portal instead of displaying the event details. 

However, when the userRole is set to 'user', it works fine, and clicking on a specific event in the calendar view only displays the event details without redirecting to the admin portal. I hope this clarifies you this issue.  As you can see in the image, when I navigate to the calendar view and click on a specific event as `user`, it only displays the event details and does not redirect to the admin portal      
   
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/30a8e03f-c08e-4d0c-8012-98ade26a5990)

**Comment by aashimawadhwa** [comment]
@rahulch07  we have some different designs and flow planned for this issue i think we might close this issue for now and make a new one when designs are finalised

**Comment by rahulch07** [comment]
Alright, got it. Would love to work on it in future! Thank you.
