### ISSUE TITLE
Bug: Superadmin can not edit the role of a user from the drop down in users section

### ISSUE THREAD

**Issue by Doraemon012** [PalisadoesFoundation/talawa-admin#1799]
**Describe the bug**
When logged in as a `Superadmin` and attempting to change a user's role, the changes appear to be successful in the drop down menu, but revert back to the original role upon page refresh.

**To Reproduce**

- Updating the User Type from the page where users are diplayed
  1. Log in as a `Superadmin`.
  2. Navigate to the `Users` tab from the sidebar.
  3. Change the role of a user using the dropdown menu on the user list page.
  4. Refresh the page.
  5. Observe that the role change made in the previous step is not retained.

- Updating the User Type from the joined organizations modal
  1. Log in as a `Superadmin`.
  2. Navigate to the `Users` tab from the sidebar.
  3. Click on the `Joined Organizations` button.
  4. Change the role of a user using the dropdown menu
  5. Notice that a toast is displayed upon successful updation of the role
  6. Refresh the page.
  7. Observe that the role change made in the previous step is retained.

**Expected behavior**
A `Superadmin` must be able to edit the role of any user, and the changes must be reflected even if the page is refreshed.

**Actual behavior**
A `Superadmin` is not able to edit the role of any user. The changes vanish as soon as the page is refreshed.

**Screenshots**

1. Updating the User Type from the page where users are diplayed

[sup_admin.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/5d716a2a-346c-4289-aacc-dfccbf28b890)

2. Updating the User Type from the joined organizations modal

[ROLE_EDIT_FROM_MODAL.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/39caec68-abbd-480b-9a0c-69dd6cb9f67d)

**Additional details**
A `Superadmin` can edit the role of a user from the joined organizations modal, a toast is also displayed on successful updation. On the other hand when the `Superadmin` tries to change the role of the user from the dropdown on the page where the users are listed, the operation is not successful and the changes are reverted upon refreshing the page.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Doraemon012** [comment]
@palisadoes 

I have some questions regarding the above issue.

As per the schema, a **user** `(User / Admin /  Superadmin)` can join multiple organizations, and an admin can oversee multiple organizations.

In the existing design, a `Superadmin` has the ability to modify a user's role from the joined organizations modal. This is depicted in the image below.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/2a5bb3f1-90ba-45d6-a585-da783b6752c9)

However, I'm unsure about the purpose of this dropdown menu:

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/8a0a5616-b71c-4b17-9cbf-8bb5b7958125)

Could you please clarify its functionality ?

Additionally, here's a snapshot of the current Users page in the admin portal:

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/794298be-9c39-462b-ae9c-423d3f69d50f)

**Comment by palisadoes** [comment]
1. This is what the Figma file shows as the new page layout

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/3a12e158-3988-4f76-9891-d41ff6588ff1)

1. Clicking through on a user should bring up their profile:

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/9be5cada-64e0-4d81-9964-22c0ffa8bd7b)

1. @Doraemon012  There is an issue assigned to @pranshugupta54 to fix the user profile layout, using the existing screen. But we don't have a redesign of the screen you are referring to.
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1615

I'd suggest the following:

1. @Doraemon012 close this issue and create one to fix the screen you mentioned. 
2. @pranshugupta54 add the update of the user privileges on your screen

In both cases please wait for the responses below from our mentor design team.

- @aashimawadhwa and @rishav-jha-mech Please let us know your thoughts.

**Comment by pranshugupta54** [comment]
@palisadoes, looks like you got the wrong screen. You're referring to Org > People screen. He's talking about Users screen which contains all the users of all the Organizations.


This is the new design according to Figma file
<img width="747" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/f6d6b17e-863a-45c0-9f58-288bc0388f8d">



But we need to change this design, instead of having dropdown on the role we should have 2 buttons there :
Joined and Blocked
<img width="224" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/66ca7eeb-7c46-422d-8b35-69c7804f4a89">

On clicking "Joined Orgs", a modal opens and shows this following things:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/ba1ec6d9-f8a6-49ec-8801-06abc4dfb102)

**Comment by palisadoes** [comment]
Now that we have fixed `userType` we need to change the workflow changes will need to be made.

1. The _tentative_ long term design aim is to have the Users' Roles screen to look like the Organization People screen
2. Clicking through on the person's name would bring up the profile page and the new Organizations tab would be where you would change the person's role.
3. The Figma isn't up to date

We need @aashimawadhwa and @rishav-jha-mech to verify the design workflow

It's good that this was caught. It's both a design change and functionality bug. (The dropdown is unnecessary and wrong because roles are now per organization. It shouldn't be visible)

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/f3b26361-e277-4aab-957a-cc06e9f8bebd)

**Comment by palisadoes** [comment]
@Doraemon012

- Rather than waiting on the others. The dropdown that you identified must be removed. You have rightly identified that it doesn't make sense with the new per organization functionality. Please remove it

@aashimawadhwa and @rishav-jha-mech 

- We are going to need issues for this design change. We may have missed it.

**Comment by Doraemon012** [comment]
@palisadoes 
I understand the issue. I can fix it, please assign it to me.

**Comment by varshith257** [comment]
Maybe a related issue:

- https://github.com/PalisadoesFoundation/talawa-api/issues/1422
