### ISSUE TITLE
Upgrade react-toastify from 9.1.3 to 10.0.4

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1950]
## Rationale
1. This was previously attempted by the automated dependabot job but the PR tests failed.
1. This issue has been created to fix the issue as there may be multiple dependency requirements that need updating

This is a major revision upgrade and many files may need to be updated to the new syntax, functions, methods and classes

## Task

1. Upgrade [react-toastify](https://github.com/fkhadra/react-toastify) from 9.1.3 to 10.0.4.
1. Existing configurations must not be modified 
1. No other functionality must be affected
1. All tests must be valid and pass

## Background Failing PRs
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1945

**Comment by adithyanotfound** [comment]
I want to work on this issue. Please assign this issue to me

**Comment by varshith257** [comment]
Here you go @adithyanotfound !

**Comment by adithyanotfound** [comment]
The reason for react-toastify version 10.0.4 not working is because it require react version 18 or above.
<img width="679" alt="Screenshot 2024-08-03 at 5 44 34 PM" src="https://github.com/user-attachments/assets/2c173879-21fa-4d45-896f-a7ccd9154090">
The current version of react is 17.0.2. Should I proceed to upgrade react?
It will involve changing the render method to createRoot in multiple files.

**Comment by varshith257** [comment]
Yes, proceed. We need to be up to date with packages.

Reference:
https://react.dev/blog/2022/03/08/react-18-upgrade-guide
