### ISSUE TITLE
Refactor CSS files in src/screens/PageNotFound

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-admin#2524]
# Refactor CSS files in src/screens/PageNotFound

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

**Comment by mandeepnh5** [comment]
can i work on this issue

**Comment by mandeepnh5** [comment]
Thank you for assigning me the issue, I have one doubt so basically i have to refactor code such that all the classes and media queries used in PageNotFound.module.css should now be present ./styles/app.module.css and later the PageNotFound.module.css will be deleted and I should import all classes from ./styles/app.module.css file?
I am new here, so it will be helpful if anyone clarifies my doubt

**Comment by mandeepnh5** [comment]
I have created the pull request please check it

**Comment by mandeepnh5** [comment]
@palisadoes can I know what what is the issue in my PR, I am new here so I am not sure

**Comment by palisadoes** [comment]
This PR needed to be closed.

The source and target PR branches are the same. This means that our reviewers will not be able to checkout the changes and test on their systems using this methodology which will cause a rejection error:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

Please follow these steps:

1. Create a new branch with a different name in your local repository
    1. Make sure the branch name is named differently from the required target branch in the PR
    1. Use the `git checkout -b` command to do this.
3. Resubmit your PR

**Comment by mandeepnh5** [comment]
@palisadoes Ok thanks for guidance I have created PR again please check

**Comment by palisadoes** [comment]
We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

This policy is stated as a pinned post in all our Talawa repositories. Our YouTube videos explain why this practice is not acceptable to our Community.

In most cases you don’t have to close the PR to trigger the GitHub workflow to run again. Making a new commit and pushing it to your GitHub account will normally be sufficient.

Unfortunately, if this continues we will have to close the offending PR and unassign you from the issue.

![image](https://github.com/user-attachments/assets/34155071-9c95-4dd7-97d0-77c1dc166c36)

**Comment by mandeepnh5** [comment]
Thank you soo much for guidance looking forward to contribute more
