### ISSUE TITLE
Feature Request: Remove captcha from login page

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#475]
**Is your feature request related to a problem? Please describe.**
we can remove the captcha from the login page as it is unnecessary to verify re-cpatcha on every login .

**Describe the solution you'd like**
removing it from the login page, as discussed in the meeting.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
@palisadoes

**Comment by palisadoes** [comment]
@aashimawadhwa Please remove ReCAPTCHA completely. We can restore it later. I don't want it to cause people to not want to contribute to the project due to:

1. Additional installation complexity
2. Instability of the feature

Please remove it from the INSTALLATION.md files for Talawa-Admin and Talawa-API. Create the necessary issues when required.

**Comment by aashimawadhwa** [comment]
Okay on it @palisadoes

**Comment by aashimawadhwa** [comment]
@palisadoes  should I comment the code or completely remove it ?

**Comment by palisadoes** [comment]
Comment it out. Someone can use it as a reference later.

**Comment by palisadoes** [comment]
@tasneemkoushar @anwersayeed If we comment out the code will it show up in TSDocs?

**Comment by xoldyckk** [comment]
@aashimawadhwa recaptcha is correctly implemented on the server. Here are the 3 possible scenarios for the intermittent behaviour:-

1. Incompatible site and secret keys for recaptcha.
2. Talawa-admin's implementation for handling it is broken. Server side graphql resolver always sends a boolean to tell whether the recaptcha failed or passed.
3. Google's recaptcha service is broken.

I'd say the it's cuz of scenario 1 and 2.

So, there's no reason for removing it completely. I agree that this check should not bother the contributers even if it's working. But it is an important check to prevent against bots overloading the server with requests. Here's what you can do:-

1. Fix the client-side implementation for it.
2. Make it so that check is only asked for in testing and production environments.

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa Please remove ReCAPTCHA completely. We can restore it later. I don't want it to cause people to not want to contribute to the project due to:
> 
>     1. Additional installation complexity
> 
>     2. Instability of the feature
> 
> 
> Please remove it from the INSTALLATION.md files for Talawa-Admin and Talawa-API. Create the necessary issues when required.

@xoldyckk  please refer to this.

**Comment by xoldyckk** [comment]
> > @aashimawadhwa Please remove ReCAPTCHA completely. We can restore it later. I don't want it to cause people to not want to contribute to the project due to:
> > ```
> > 1. Additional installation complexity
> > 
> > 2. Instability of the feature
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please remove it from the INSTALLATION.md files for Talawa-Admin and Talawa-API. Create the necessary issues when required.
> 
> @xoldyckk please refer to this.

What about it?

**Comment by aashimawadhwa** [comment]
It is a temporary removal to make the contribution easy, I am commenting the code, this can be restored anytime later.
with the reference of the changes. 
@palisadoes @xoldyckk

**Comment by xoldyckk** [comment]
> It is a temporary removal to make the contribution easy, I am commenting the code, this can be restored anytime later. with the reference of the changes. @palisadoes @xoldyckk

@palisadoes told me that it has intermittent behaviour so I provided my input on that. If it's working fine and you're commenting it just to make it easier for contributers, you shouldn't. 

Instead use this approach:-
```
Make it so that check is only asked for in production environments
```

**Comment by palisadoes** [comment]
@aashimawadhwa Do you think we can fix it? The more important concern is the intermittent results, rather than the complexity.

**Comment by aashimawadhwa** [comment]
okay I will research on it and figure out 

- firstly If I can check for the intermittent behavior because after 3 4 times of loggin in and out the captcha starts acting out in development mode, we can try to fix that and 

- If it is not achievable we can use @xoldyckk  approach to remove it from testing and development and let it be in the production .

WDYT @palisadoes ?

**Comment by palisadoes** [comment]
Please proceed.

**Comment by xoldyckk** [comment]
> okay I will research on it and figure out
> 
> * firstly If I can check for the intermittent behavior because after 3 4 times of loggin in and out the captcha starts acting out in development mode, we can try to fix that and
> * If it is not achievable we can use @xoldyckk  approach to remove it from testing and development and let it be in the production .
> 
> WDYT @palisadoes ?

If it can't be fixed even after implementing it correctly in talawa-admin, it means it's a problem with google itself. Then it should just be replaced with another similar service or removed completely.

**Comment by aashimawadhwa** [comment]
I will work on it and discuss my findings @xoldyckk @palisadoes

**Comment by aashimawadhwa** [comment]
So captcha is implemented correctly on the talwa admin and it's working fine and stops working sometimes for no specific reason.
Now I feel the Following About it :

-  ReCAPTCHA might block the simplest of bots, but it makes for a frustrating user experience and it does not serve as sufficient protection against the security threats that plague companies today. For that, we need a bot protection solution.

Now I was thinking why cannot we let it be on the register page and just remove it from the login page!?
@palisadoes

**Comment by anshgoyalevil** [comment]
> 

We should not remove the ReCAPTCHA from login page. Here are a few reasons:
- It prevents the bot networks to attempt DDoS attacks. What that basically means is, the bot nets try to create multiple api requests for signing in using the fake login data, which will increase the load on server.
- This would make the server to deny the other genuine requests, because of heavy load.

What I would recommend in this situation is:
- Just add a CAPTCHA test for cases when there have been failed login attempts for a given user. This is what lots of websites currently do (all popular email services for instance) and is much less invasive.
- You may check for the failed login attempts of the current IP address, and then apply a condition like if the failed attempts > 4, show captcha, else, don't show.

**Comment by aashimawadhwa** [comment]
Does all this implies on this condition as well? @anshgoyalevil we're just removing it from login,  it's on signup page(where the user register themselves) it can prevent everything you mentioned in the description above.

**Comment by anshgoyalevil** [comment]
> Does all this implies on this condition as well? @anshgoyalevil we're just removing it from login, it's on signup page(where the user register themselves) it can prevent everything you mentioned in the description above.

The false API calls could be made from the login form also. Isn't it?

Securing the login forms is as important as securing registration forms. Registration forms are vulnerable to bot spams, so they need recaptcha, while login forms are vulnerable to malicious bot attempts, so they too need recaptcha.

What's your opinion on this @xoldyckk ?

**Comment by aashimawadhwa** [comment]
If we're planning to keep it i think then we can close this issue. the recapctha is working fine, It allows the user to work for an hour or so and gets disabled automatically I tired from google Chrome. It can be an issue in my previous browser.
@palisadoes.

**Comment by palisadoes** [comment]
I am not on favor of removing a security feature if there is a way to make it reliable. We seen to have a solution to the intermittent responses, let's give it a try.

**Comment by aashimawadhwa** [comment]
> I am not on favor of removing a security feature if there is a way to make it reliable. We seen to have a solution to the intermittent responses, let's give it a try.



> If we're planning to keep it i think then we can close this issue. the recapctha is working fine, It allows the user to work for an hour or so and gets disabled automatically I tired from google Chrome. It can be an issue in my previous browser. @palisadoes.

@palisadoes  please refer to this.

**Comment by palisadoes** [comment]
OK. Close the issue and PR.

**Comment by xoldyckk** [comment]
@aashimawadhwa take a look at [this](https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do)
