### ISSUE TITLE
Choosing the Display image for an Organization

### ISSUE THREAD

**Issue by anwersayeed** [PalisadoesFoundation/talawa-admin#477]
**Describe the bug**
When we create a new organization and select an image for its display on the organization list page, the organization gets created but the image fails to load.

**To Reproduce**

1. Go to Organization List page.
2. Click on "Create Organization".
3. Fill all the details and chose an image.
4. Finally, click on "Create Organization" in the form below.

**Expected behavior**
Organization should be created and the image must load.

**Actual behavior**
Organization is created but the image does not load.

**Screenshots**
![1](https://user-images.githubusercontent.com/57287988/219848000-2be101ab-d7dc-4901-91b6-d804898dc8f7.PNG)
![2](https://user-images.githubusercontent.com/57287988/219848007-a8342725-01a9-4919-8431-3b1d9a8e6ceb.PNG)

**Comment by anurag0006** [comment]
I would like to work on this issue, ease assign it to me

**Comment by anwersayeed** [comment]
> I would like to work on this issue, ease assign it to me and i think this might be an issue from api side🤔🤔

You can proceed.

**Comment by anwersayeed** [comment]
> I would like to work on this issue, ease assign it to me and i think this might be an issue from api side🤔🤔

Have you been assigned any issue before this?

**Comment by anurag0006** [comment]
yeah, i have already worked on many issues and have around 5 PR too

**Comment by anwersayeed** [comment]
> yeah, i have already worked on many issues and have around 5 PR too in talawa-admin

Ideally you should be working on no more than two issues at a time.

**Comment by anurag0006** [comment]
> > yeah, i have already worked on many issues and have around 5 PR too in talawa-admin
> 
> Ideally you should be working on no more than two issues at a time.

Yeah, am not working on any issue at the time, my PRs are already merged

**Comment by rishav-jha-mech** [comment]
I think i will be able to solve this issue, please assign this issue to me.

**Comment by anwersayeed** [comment]
@rishav-jha-mech Have you been assigned any issue before this?

**Comment by rishav-jha-mech** [comment]
No

**Comment by anwersayeed** [comment]
@rishav-jha-mech Alright, I am assigning this issue to you. Good Luck!

**Comment by anwersayeed** [comment]
> I think i will be able to solve this issue, please assign this issue to me.

@rishav-jha-mech  We wish to make as few changes as possible to the current design. So, we require no new CSS or responsive design now, rather, work only on previously disabled or improperly implemented functionalities.

**Comment by noman2002** [comment]
@anwersayeed @palisadoes We already have this for one of our gsoc ideas. Should we have this as an issue now ?

**Comment by palisadoes** [comment]
@noman2002 This is a feature that currently does not work. I'll update the ideas page to add clarity .

**Comment by noman2002** [comment]
> @noman2002 This is a feature that currently does not work. I'll update the ideas page to add clarity .

Okay. Alright

**Comment by rishav-jha-mech** [comment]
I have found solution to this so basically if we want to upload files from the client side we need to install some third party packages as stated in the official documentation of Apollo Client.

`Apollo Client doesn't support a file upload feature out of the box. If you'd like to enable file upload capabilities, you will have to set Apollo Client up manually with a 3rd party package.`

There is no file uploading functionality in the entire repository right now, even though the backend code is ready for it. So we need to install a third party package like `apollo-upload-client`, and set it up so that file uploading can work in our application.
Now because this is a big change, i wanted to know what should be done ?

P.S. The request is being sent with the content-type header as 'application/json', but if we need to send an image to the backend then we need to set the content-type as `multipart/form-data`. at the present we cant change the content type so we can't upload pictures.

**Comment by palisadoes** [comment]
@rishav-jha-mech the GraphQL file management dependency has recently been deprecated and doesn't work. It will need to be rectified as a project. We are working on a quick fix for this with this issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1080

**Comment by palisadoes** [comment]
Please follow developments with that issue.

**Comment by rishav-jha-mech** [comment]
This feature is ready !
As soon as https://github.com/PalisadoesFoundation/talawa-api/pull/1086 is merged I will open the PR.

**Comment by rishav-jha-mech** [comment]
Screenshots


![Talawa Organizations - Google Chrome 25-02-2023 17_23_53](https://user-images.githubusercontent.com/76212518/221355472-fa99832f-04bd-40d8-a0b2-7a548b976d66.png)
![Talawa Organizations - Google Chrome 25-02-2023 17_24_20](https://user-images.githubusercontent.com/76212518/221355462-34db53df-4e21-4c50-8724-8bf987be0317.png)


## The only problem is that I have to change some CSS properties , otherwise these screens would look like ...

![Talawa Organizations - Google Chrome 25-02-2023 17_22_33](https://user-images.githubusercontent.com/76212518/221355664-21374316-b899-4031-a529-84ec4928bfec.png)

![Talawa Organizations - Google Chrome 25-02-2023 17_29_39](https://user-images.githubusercontent.com/76212518/221355659-7e60d76b-31dd-4cb1-aa3b-e3a4471f4917.png)
