### ISSUE TITLE
Remove the Contribution Page

### ISSUE THREAD

**Issue by tasneemkoushar** [PalisadoesFoundation/talawa-admin#484]
**Is your feature request related to a problem? Please describe.**
We have a dedicated Contribution page, to see the contribution done to your organizations. We don't want this feature to be implemented as of now.

![Screenshot from 2023-02-19 14-06-31](https://user-images.githubusercontent.com/58592306/219937829-c6d0b720-84e4-48f2-89b8-ea667155ec73.png)

**Describe the solution you'd like**
Remove the Contribution page from the admin panel.

**Approach to be followed (optional)**
we want to minimize changes to the existing design. Hence no new CSS, no new responsive design, just the enabling of previously disabled or incorrectly implemented features.

**Comment by anshgoyalevil** [comment]
I can work upon this issue. Could you please assign it to me.

**Comment by anshgoyalevil** [comment]
@tasneemkoushar @anwersayeed 
Should I remove the contributions page completely (Which will involve removing all of its tests, and components, or should I just remove it from the header (Router), so that no one can access it from Admin Dashboard directly.

The benefits of removing it only from the Header are:
- We would get a room for adding something like contributions in the future, since, we would already have the components code for it ready, along with its test code.

If we don't have any plan to add anything like contributions in future, I would recommend removing it completely.

What are your thoughts on this?

**Comment by palisadoes** [comment]
We'll most likely be moving the feature to be a plugin based on GSoC ideas. The underlying code will be a good guide. So remove the link for now. It's not ideal, but I'd like to speed up bug fix work in other areas
