### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by KhushiTayal** [PalisadoesFoundation/talawa-admin#762]
**Describe the bug**
The display image is not getting updated inside Settings->Update Organization->Display Image

**Expected behavior**
The display image should be updated when we upload a new image.

**Actual behavior**
Can upload the display image but it is not getting updated.

**Comment by KhushiTayal** [comment]
@palisadoes please assign this issue to me.

**Comment by palisadoes** [comment]
1. Please change the title of this issue so that it will be more easily searchable.
2. Fill in the template for the issue as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done. It also asks for screenshots which would help illustrate the nature of your concerns

I'm going to close this. Please follow the guidelines. It helps everyone.
