### ISSUE TITLE
Add appropriate spacing for better UX

### ISSUE THREAD

**Issue by ssaumyaa7** [PalisadoesFoundation/talawa-admin#78]
All the components should have a uniform padding margin, the inconsistency will lead to bad UI/UX.

Further, the login page is not placed on the page properly. It is in the corner leading to not so good display.

Many of the components fail to follow the same and are different from the Figma design suggested.

@palisadoes sir would like to work on this issue.

**Additional details**
GitHub Externship : 19-05_Sin666_tfa_262

**Comment by yasharth291** [comment]
@ssaumyaa7  it is not recommended to use padding

**Comment by ssaumyaa7** [comment]
@yasharth291 keeping that in mind will add margins, as there are places where buttons and fields need to be placed a little differently else the buttons would look a little too close for the view 

for example without any margins :
![m1](https://user-images.githubusercontent.com/64359826/121652191-06656180-cab9-11eb-9e00-8cc061851bbd.PNG)

After adding margins :
![m2](https://user-images.githubusercontent.com/64359826/121652238-11b88d00-cab9-11eb-93d7-a8806e9edf33.PNG)

**Comment by DangaRanga** [comment]
Thanks much for the insight's Saumya, responsiveness for the varying screen sizes is something we do need to achieve for all of the screen sizes on Talawa going forward. 

I can also see that this issue's title was duplicated a few times, but at first glance it doesn't provide much detail as to what the issue is about so please use descriptive titles when creating issues.

One appropriate title for a parent issue for the issues you've created could potentially be:
`Ensure that the Screens on Talawa Admin are Responsive`

And the child issues could speak for the respective components that you've highlighted (such as the Login form in this instance)


> @ssaumyaa7 it is not recommended to use padding


@yasharth291 
It is recommended to use padding where appropriate (such as creating space inside of elements). You may check out this [article ](https://medium.com/frontendshortcut/margin-vs-padding-c1fc8ea8bfaf)for further clarity on the topic

**Comment by ssaumyaa7** [comment]
@DangaRanga sir, I Will be more descriptive with the title while raising the issue.

@palisadoes sir, please assign me this issue.

Thank you.

**Comment by palisadoes** [comment]
@ssaumyaa7 You can also ask @DangaRanga to assign issues in future.
